### ISSUE TITLE
servant-subscriber 0.6.0.1 build failure with servant 0.14

### ISSUE THREAD

**Issue by DanBurton** [eskimor/servant-subscriber#17]
As seen on the Stackage build server:

```
[1 of 8] Compiling Servant.Subscriber.Subscribable ( src/Servant/Subscriber/Subscribable.hs, dist/build/Servant/Subscriber/Subscribable.o )

src/Servant/Subscriber/Subscribable.hs:91:10: error:
    • Number of parameters must match family declaration; expected 2
    • In the type instance declaration for ‘MkLink’
      In the instance declaration for ‘HasLink (Subscribable :> sub)’
   |
91 |     type MkLink (Subscribable :> sub) = MkLink sub
   |          ^^^^^^
```

I was able to reproduce this locally like so:

```bash
stack unpack servant-subscriber-0.6.0.1 && cd servant-subscriber-0.6.0.1
edit stack.yaml # add the following stack.yaml
stack build --test --bench --no-run-benchmarks
```

```yaml
# stack.yaml
resolver: nightly-2018-07-04
extra-deps:
- servant-0.14
- servant-server-0.14
```
